#pragma once

DEFINE_ENUM_TYPES(Service_t,MATCHER,GATEWAY)
DEFINE_ENUM_TYPES(DomainObjects_t,ORDERLOOKUP,SYMBOLLOOKUP,FIRMLOOKUP)
DEFINE_ENUM_TYPES(MatcherEvents_t,NEW_ORDER,REPLACE_ORDER,CXL_ORDER)

DEFINE_ENUM_TYPES(ClientType_t,GOOD,BAD)
DEFINE_ENUM_TYPES(EntityStatus_t,GOOD,BAD)

DEFINE_ENUM_TYPES(Side_t,BUY,SELL)

DEFINE_ENUM_TYPES(ExecInst_t,BUY,SELL)
DEFINE_ENUM_TYPES(OrdType_t,BUY,SELL)
DEFINE_ENUM_TYPES(OpenClose_t,BUY,SELL)
DEFINE_ENUM_TYPES(TimeInForce_t,BUY,SELL)
DEFINE_ENUM_TYPES(OrdStatus_t,BUY,SELL)
DEFINE_ENUM_TYPES(AutoCancel_t,BUY,SELL)
