#pragma once

// All enums used internally in DBTable (DomainObject) goes here and have no mapped fix code.  
//API Enums mapped with fix code are in DataDictionary.hpp with exchange namespace
DEFINE_ENUM_TYPES(Service_t,MATCHER,GATEWAY)
DEFINE_ENUM_TYPES(DomainObjects_t,ORDERLOOKUP,SYMBOLLOOKUP,FIRMLOOKUP)
DEFINE_ENUM_TYPES(MatcherEvents_t,NEW_ORDER,REPLACE_ORDER,CXL_ORDER)

DEFINE_ENUM_TYPES(ClientType_t,CUSTOMER,FIRM,BROKER,DEALER)
DEFINE_ENUM_TYPES(EntityStatus_t,ACTIVE,DISABLE,BLOCK)

DEFINE_ENUM_TYPES(Side_t,BUY,SELL)

DEFINE_ENUM_TYPES(OrdType_t,MARKET,LIMIT,STOP,STOPLIMIT)
DEFINE_ENUM_TYPES(OpenClose_t,OPEN,CLOSE)
DEFINE_ENUM_TYPES(TimeInForce_t,DAY,GTC,IOC,FOK,GTX,GTD)
DEFINE_ENUM_TYPES(OrdStatus_t,NEW,PARTIAL,FILLED,DONE_TODAY,CANCELED,UROUT,CANCEL_PENDING,STOPPED,REJECTED,NEW_PENDING,EXPIRED,REPLACE_PENDING)

DEFINE_ENUM_TYPES(AutoCancel_t,AUTO_CANCEL_ON,AUTO_CANCEL_OFF)
DEFINE_ENUM_TYPES(ExecInst_t,NONE,RFQ,AON)


